import type { PracticeConcept, PracticeLevel, PracticeProgram } from "./types";
// Same import precedent as `src/lessons/recordings.ts`: real production code importing
// committed trace/output JSON straight out of `tests/fixtures/`, not duplicated into src/.
import expectedOutputJson from "../../tests/fixtures/practice/expected-output.json";

/** D27's 8 concepts. The 6 basics offer both exercise types; binary search and bubble sort are
 * flowchart-only (D33: reassembling an algorithm from shuffled lines tests memory, not
 * understanding) — see `docs/decisions/004-practice-scope-split.md`. */
export const PRACTICE_CONCEPTS: PracticeConcept[] = [
  { id: "for-loops", title: "For loops", exercises: ["reverse", "flowchart"] },
  {
    id: "index-loops",
    title: "Index loops",
    exercises: ["reverse", "flowchart"],
  },
  { id: "if-else", title: "If / else", exercises: ["reverse", "flowchart"] },
  {
    id: "while-loops",
    title: "While loops",
    exercises: ["reverse", "flowchart"],
  },
  { id: "functions", title: "Functions", exercises: ["reverse", "flowchart"] },
  { id: "recursion", title: "Recursion", exercises: ["reverse", "flowchart"] },
  { id: "binary-search", title: "Binary search", exercises: ["flowchart"] },
  { id: "bubble-sort", title: "Bubble sort", exercises: ["flowchart"] },
];

export const PRACTICE_LEVELS: PracticeLevel[] = ["easy", "medium", "hard"];

/** Globbed rather than 24 hand-written `?raw` imports — the glob precedent is
 * `src/lessons/recordings.ts`. A glob can silently return fewer files than expected, so
 * `registry.test.ts` asserts all 24 expected ids resolve; a typo'd filename fails a test instead
 * of quietly shrinking the corpus. */
const SOURCES = import.meta.glob("./programs/*.py", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

export const PRACTICE_PROGRAMS: PracticeProgram[] = PRACTICE_CONCEPTS.flatMap(
  (concept) =>
    PRACTICE_LEVELS.flatMap((level) => {
      const id = `${concept.id}-${level}`;
      const source = SOURCES[`./programs/${id}.py`];
      return source === undefined
        ? []
        : [{ id, conceptId: concept.id, level, source }];
    }),
);

export function getProgram(id: string): PracticeProgram | undefined {
  return PRACTICE_PROGRAMS.find((program) => program.id === id);
}

export function programsForConcept(conceptId: string): PracticeProgram[] {
  return PRACTICE_PROGRAMS.filter((program) => program.conceptId === conceptId);
}

/** The output an exercise is shown before any attempt — generated by the real engine and
 * committed (`registry.test.ts`'s `toMatchFileSnapshot`), never typed, so D34 holds end to end. */
const EXPECTED_OUTPUT = expectedOutputJson as Record<string, string>;

export function getExpectedOutput(programId: string): string {
  const output = EXPECTED_OUTPUT[programId];
  if (output === undefined) {
    throw new Error(
      `No committed expected output for practice program "${programId}".`,
    );
  }
  return output;
}
